version: '3.8'

networks:
  pixel-gaming:

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pixelgaming
    ports:
      - "5432:5432"
    networks:
      - pixel-gaming

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: octa.quinteroo@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    networks:
      - pixel-gaming

  client:
    image: pixelgaming-client
    build: ./client
    container_name: pixelgaming-client
    ports:
      - "81:80"
    networks:
      - pixel-gaming

  server:
    image: pixelgaming-server
    depends_on:
      - postgres
    container_name: pixelgaming-server
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: postgres  # Usar el nombre del servicio aquí en lugar de una dirección IP fija
      DB_PORT: 5432
      DB_NAME: pixelgaming
    ports:
      - "8080:8080"
    networks:
      - pixel-gaming
